name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `autohand ...`
        2. Enter '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Autohand Version
      description: Run `autohand --version` to get this
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (x64)
        - Linux (ARM64)
        - Windows (x64)
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: e.g., macOS 14.2, Ubuntu 22.04, Windows 11
      placeholder: "macOS 14.2"

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      options:
        - curl install script
        - npm/bun global install
        - Built from source
        - GitHub release binary
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: LLM Model (if applicable)
      description: Which model were you using?
      placeholder: "openai/gpt-4o"

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any error messages or logs here
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration (optional)
      description: Relevant parts of your ~/.autohand/config.json (remove sensitive data like API keys)
      render: json

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues that describe this bug
          required: true
        - label: I have removed any sensitive information (API keys, personal data) from the logs/config
          required: true
