/**
 * @license
 * Copyright 2026 Autohand AI LLC
 * SPDX-License-Identifier: Apache-2.0
 */
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Compiled release binaries carry no `dist/skills/builtin` or
 * `dist/agents/builtin` directories, so the built-in skills and agents are
 * embedded as a string module and materialized on first run. Re-run this
 * script after editing anything under those directories; a unit test fails
 * when the generated module drifts from the sources.
 */
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BUILTIN_ASSET_ROOTS = ['skills/builtin', 'agents/builtin'] as const;
const OUTPUT_PATH = path.join(repoRoot, 'src', 'generated', 'builtinAssets.ts');

async function walk(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...await walk(fullPath));
    } else if (entry.isFile()) {
      files.push(fullPath);
    }
  }
  return files;
}

export async function collectBuiltinAssets(root = repoRoot): Promise<Record<string, string>> {
  const assets: Record<string, string> = {};
  for (const assetRoot of BUILTIN_ASSET_ROOTS) {
    const absoluteRoot = path.join(root, 'src', assetRoot);
    for (const file of await walk(absoluteRoot)) {
      const relative = path.relative(path.join(root, 'src'), file).split(path.sep).join('/');
      assets[relative] = await readFile(file, 'utf8');
    }
  }
  return assets;
}

export function digestBuiltinAssets(assets: Record<string, string>): string {
  const hash = createHash('sha256');
  for (const key of Object.keys(assets).sort()) {
    hash.update(key).update('\0').update(assets[key] ?? '').update('\0');
  }
  return hash.digest('hex').slice(0, 16);
}

export function renderBuiltinAssetsModule(assets: Record<string, string>): string {
  const digest = digestBuiltinAssets(assets);
  const entries = Object.keys(assets)
    .sort()
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(assets[key])},`)
    .join('\n');
  return [
    '// Generated by scripts/embed-builtin-assets.ts from src/skills/builtin and src/agents/builtin; do not edit.',
    '// Regenerate with `bun run embed:builtin` after changing a built-in skill or agent.',
    `export const BUILTIN_ASSETS_DIGEST = ${JSON.stringify(digest)};`,
    '',
    'export const BUILTIN_ASSETS: Readonly<Record<string, string>> = {',
    entries,
    '};',
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const assets = await collectBuiltinAssets();
  await writeFile(OUTPUT_PATH, renderBuiltinAssetsModule(assets), 'utf8');
  console.log(`Embedded ${Object.keys(assets).length} built-in asset files into ${path.relative(repoRoot, OUTPUT_PATH)}.`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
  });
}
